
all:
	gcc -Wall -Werror -c ./src/wsdl.c -I src/include -L src/lib -lSDL3 -o ./bin/wsdl.o
	gcc -Wall -Werror -shared -o ./bin/wsdl.dll ./bin/wsdl.o -L src/lib -lSDL3
	python ./tools/zipit.py ./test.zip ./bin/wsdl.dll ./bin/wsdl.o
run:
	./main.exe
clean:
	rm ./bin/wsdl.dll
	rm ./bin/wsdl.o
push:
	call ./tools/action_push.bat
	shell rm ./tools/cm.i
	shell rm ./tools/cmtmsg.i
	shell rm ./tools/hash.i